# default folder for saving sqlite tables (near worlds, plugins, etc.)
sqlite: database

# mysql connection flags
mysql-flags: useSSL=false&autoReconnect=true&useUnicode=true&serverTimezone=UTC

# mysql connection validation (in seconds)
mysql-validation: 20